favicon: null
name: Pamelachen
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5687433
  lightness: 0.707304
  brandStrength: 0.7212675
  brandColors:
    - '#FFFFFF'
    - '#929292'
    - '#9CD7CF'
  rhythmicContrast: 0.5010741
typography_spectrum: 0.2916219
layout_spectrum: 0.1648765
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
