layout_spectrum: 0.5128894
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5687433
  brandStrength: 0.5171858
  rhythmicContrast: 0.5010741
  brandColors:
    - '#FFFFFF'
    - '#929292'
    - '#9CD7CF'
  lightness: 0.707304
typography_spectrum: 0.6858217
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Pamelachen
