collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2635625
  brandStrength: 0.2755102
  rhythmicContrast: 0.4219922
  brandColors:
    - '#FFFFFF'
    - '#929292'
    - '#9CD7CF'
  lightness: 0.8861445
typography_spectrum: 0.7534909
layout_spectrum: 0.594522
name: Pamelachen
